services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: RoomBooking
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: roombooking
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"

volumes:
  pgdata: